### ISSUE TITLE
TurboVNC no suitable authentication method available

### ISSUE THREAD

**Issue by haoyangw** [iiordanov/remote-desktop-clients#208]
Set up TurboVNC 2.2.4 on Ubuntu 20.04 and enabled only 'TLSVnc' security type with my own personal x509 certificate, but while TurboVNC Viewer on macOS connects to the server just fine, bVNC(free) complains that no suitable authentication method is available, as seen in the logcat below:
`--------- beginning of main
05-07 20:10:14.518 25439 25439 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@c5b550e
05-07 20:10:14.565 25439 25439 I RemoteCanvas: Initializing connection to: 192.168.1.240, port: 5906
05-07 20:10:14.566 25439 25474 I RemoteCanvas: Establishing VNC session to: 192.168.1.240, port: 5906
05-07 20:10:14.566 25439 25474 V RfbProto: Connecting to server: 192.168.1.240 at port: 5906
05-07 20:10:14.567 25439 25439 I InputHandlerGeneric: displayDensity, baseSwipeDist, immersiveSwipeDistance: 3.5 35.0 35.0
05-07 20:10:14.569 25439 25439 I RemoteCanvasActivity: onResume called.
05-07 20:10:14.587 25439 25474 I RfbProto: RFB server supports protocol version 3.8
05-07 20:10:14.587 25439 25474 I RfbProto: Using RFB protocol version 3.8
05-07 20:10:14.587 25439 25474 D debug   : bitPref = 0
05-07 20:10:14.587 25439 25474 I RfbProto: (Re)Selecting security type.
05-07 20:10:14.593 25439 25474 W System.err: java.lang.Exception: No suitable authentication scheme found
05-07 20:10:14.594 25439 25474 W System.err: 	at com.iiordanov.bVNC.RfbProto.negotiateAuthenticationTight(RfbProto.java:935)
05-07 20:10:14.594 25439 25474 W System.err: 	at com.iiordanov.bVNC.RfbProto.initializeAndAuthenticate(RfbProto.java:426)
05-07 20:10:14.594 25439 25474 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas.startVncConnection(RemoteCanvas.java:469)
05-07 20:10:14.594 25439 25474 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas.access$200(RemoteCanvas.java:95)
05-07 20:10:14.594 25439 25474 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas$2.run(RemoteCanvas.java:292)
05-07 20:10:14.594 25439 25474 E RemoteCanvas: java.lang.Exception: Connection to VNC server failed with reason: 
05-07 20:10:14.594 25439 25474 E RemoteCanvas: No suitable authentication scheme found
05-07 20:10:14.594 25439 25474 E RemoteCanvas: java.lang.Exception: No suitable authentication scheme found
05-07 20:10:14.594 25439 25474 E RemoteCanvas: 	at com.iiordanov.bVNC.RfbProto.negotiateAuthenticationTight(RfbProto.java:935)
05-07 20:10:14.594 25439 25474 E RemoteCanvas: 	at com.iiordanov.bVNC.RfbProto.initializeAndAuthenticate(RfbProto.java:426)
05-07 20:10:14.594 25439 25474 E RemoteCanvas: 	at com.iiordanov.bVNC.RemoteCanvas.startVncConnection(RemoteCanvas.java:469)
05-07 20:10:14.594 25439 25474 E RemoteCanvas: 	at com.iiordanov.bVNC.RemoteCanvas.access$200(RemoteCanvas.java:95)
05-07 20:10:14.594 25439 25474 E RemoteCanvas: 	at com.iiordanov.bVNC.RemoteCanvas$2.run(RemoteCanvas.java:292)
05-07 20:10:14.594 25439 25474 W System.err: java.lang.Exception: Connection to VNC server failed with reason: 
05-07 20:10:14.594 25439 25474 W System.err: No suitable authentication scheme found
05-07 20:10:14.594 25439 25474 W System.err: java.lang.Exception: No suitable authentication scheme found
05-07 20:10:14.594 25439 25474 W System.err: 	at com.iiordanov.bVNC.RfbProto.negotiateAuthenticationTight(RfbProto.java:935)
05-07 20:10:14.594 25439 25474 W System.err: 	at com.iiordanov.bVNC.RfbProto.initializeAndAuthenticate(RfbProto.java:426)
05-07 20:10:14.594 25439 25474 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas.startVncConnection(RemoteCanvas.java:469)
05-07 20:10:14.594 25439 25474 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas.access$200(RemoteCanvas.java:95)
05-07 20:10:14.594 25439 25474 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas$2.run(RemoteCanvas.java:292)
05-07 20:10:14.594 25439 25474 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas.startVncConnection(RemoteCanvas.java:478)
05-07 20:10:14.594 25439 25474 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas.access$200(RemoteCanvas.java:95)
05-07 20:10:14.594 25439 25474 W System.err: 	at com.iiordanov.bVNC.RemoteCanvas$2.run(RemoteCanvas.java:292)
05-07 20:10:14.595 25439 25474 V RfbProto: RFB socket closed
05-07 20:10:14.595 25439 25474 V RemoteCanvas: Cleaning up resources
05-07 20:10:15.019 25439 25439 I MainConfiguration: onStop called
05-07 20:10:15.717 25439 25460 D OpenGLRenderer: endAllActiveAnimators on 0x7df6135d00 (RippleDrawable) with handle 0x7d9987dcc0
05-07 20:10:15.778 25439 25439 I MainConfiguration: onStart called
05-07 20:10:15.778 25439 25439 I MainConfiguration: onResume called
05-07 20:10:15.778 25439 25439 I MainConfiguration: onResumeFragments called
05-07 20:10:15.778 25439 25439 I MainConfiguration: arriveOnPage called
05-07 20:10:16.233 25439 25439 V RfbProto: RFB socket closed
05-07 20:10:16.233 25439 25439 V RemoteCanvas: Cleaning up resources`
I've also tried tunneling TurboVNC over SSH on the **same server**, which works just fine. To troubleshoot the issue, I've git clone-d your repository and added some debug code in com.iiordanov.bVNC.RfbProto.java, under the method [selectSecurityType](https://github.com/iiordanov/remote-desktop-clients/blob/09c7b2d61ee29deacc8a9be9e60de7d1348d6c90/bVNC/src/main/java/com/iiordanov/bVNC/RfbProto.java#L587) that 1) repeats the [securityType loop](https://github.com/iiordanov/remote-desktop-clients/blob/09c7b2d61ee29deacc8a9be9e60de7d1348d6c90/bVNC/src/main/java/com/iiordanov/bVNC/RfbProto.java#L604) and reports all the securitytypes detected to be supported by my server to logcat, and 2) reports the connType detected. I installed my modified debug variant of bVNC free and after attempting to connect to my X509 encrypted TurboVNC server, from logcat, I see that bVNC detects support for both security types [16](https://github.com/iiordanov/remote-desktop-clients/blob/09c7b2d61ee29deacc8a9be9e60de7d1348d6c90/bVNC/src/main/java/com/iiordanov/bVNC/RfbProto.java#L73) and [19](https://github.com/iiordanov/remote-desktop-clients/blob/09c7b2d61ee29deacc8a9be9e60de7d1348d6c90/bVNC/src/main/java/com/iiordanov/bVNC/RfbProto.java#L76), which are secTypeTight and secTypeVeNCrypt, respectively. At the same time, logcat reports that the connType detected was [4](https://github.com/iiordanov/remote-desktop-clients/blob/09c7b2d61ee29deacc8a9be9e60de7d1348d6c90/bVNC/src/main/java/com/iiordanov/bVNC/Constants.java#L35), VeNCrypt. After reading through the selectSecurityType code in RfbProto.java, I figured that a VNC Server cannot simultaenously support both Tight and Vencrypt securityTypes, and since your code prioritises Tight securityType the moment it's detected, it appears that bVNC free fails to connect to my server as it wrongly attempts to connect to my X509 encrypted server with either None or Vnc authType(which from your code appears to be the only two supported by Tight securityType). To test out my theory, I modified your code again by wrapping a `if(connType != Constants.CONN_TYPE_VENCRYPT) {` around the [SecTypeTight loop](https://github.com/iiordanov/remote-desktop-clients/blob/09c7b2d61ee29deacc8a9be9e60de7d1348d6c90/bVNC/src/main/java/com/iiordanov/bVNC/RfbProto.java#L604), and with this change, bVNC free successfully connects to my TurboVNC server with only x509vnc securitytype flawlessly. From logcat, I see that with this change, bVNC correctly chooses to connect to my Server using Vencrypt authType and secType. Perhaps you want to consider modifying the selectSecurityType method to make secTypeTight and secTypeVencrypt mutually exclusive? I'm not sure why TurboVNC server broadcasts support for both secTypes, but as the two cannot be used at the same time anyway, I believe this code change is intended behavior. And it would definitely help out any TurboVNC + Android users out there, as few as there may be(it would definitely help me out). Thanks a ton for your hard work!

**Comment by iiordanov** [comment]
Thanks for the investigation. A couple of points and clarifications.

1) According to the TurboVNC docs: https://cdn.rawgit.com/TurboVNC/turbovnc/2.2.5/doc/index.html
TLSVnc uses Anonymous TLS ciphers which *should not work* with bVNC at all :), so you should not be enabling this mode *at all*. What you probably want is one of X509Vnc, or X509Plain, or UnixLogin, most probably.

2) I could not reproduce this on my system because I'm not familiar with TurboVNC at all and don't have time to figure out all the parameters you used to launch it.

It works fine with these options and appears to use my .vnc/passwd file to check the password. The command-line I used:

/opt/TurboVNC/bin/vncserver -x509key /etc/ssl/certs/ssl-cert-snakeoil.key -x509cert /etc/ssl/certs/ssl-cert-snakeoil.pem :13 -geometry 1920x1080

Looks like it ignores my x509 key settings, not sure why, and in my case:

secType == RfbProto.SecTypeTight
authType == RfbProto.AuthVNC, VNC authentication needed

I am adding some more logging to the beta version of bVNC, please provide the logcat from that with the reproduced error and how you configure/launch TurboVNC.

**Comment by iiordanov** [comment]
Please reopen with further details if you have time to test and capture logcat.
