### ISSUE TITLE
Unable to build bVNC with docker

### ISSUE THREAD

**Issue by seyrenhe** [iiordanov/remote-desktop-clients#225]
**host os: Archlinux**

docker logs:

Starting docker_remote-clients_1 ... done
Attaching to docker_remote-clients_1
remote-clients_1  | Warning: Could not create settings
remote-clients_1  | java.lang.IllegalArgumentException
remote-clients_1  | 	at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.<init>(SdkManagerCliSettings.java:428)
remote-clients_1  | 	at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:152)
remote-clients_1  | 	at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:134)
remote-clients_1  | 	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:57)
remote-clients_1  | 	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
remote-clients_1  | Usage:
remote-clients_1  |   sdkmanager [--uninstall] [<common args>] [--package_file=<file>] [<packages>...]
remote-clients_1  |   sdkmanager --update [<common args>]
remote-clients_1  |   sdkmanager --list [<common args>]
remote-clients_1  |   sdkmanager --licenses [<common args>]
remote-clients_1  |   sdkmanager --version
remote-clients_1  | 
remote-clients_1  | With --install (optional), installs or updates packages.
remote-clients_1  |     By default, the listed packages are installed or (if already installed)
remote-clients_1  |     updated to the latest version.
remote-clients_1  | With --uninstall, uninstall the listed packages.
remote-clients_1  | 
remote-clients_1  |     <package> is a sdk-style path (e.g. "build-tools;23.0.0" or
remote-clients_1  |              "platforms;android-23").
remote-clients_1  |     <package-file> is a text file where each line is a sdk-style path
remote-clients_1  |                    of a package to install or uninstall.
remote-clients_1  |     Multiple --package_file arguments may be specified in combination
remote-clients_1  |     with explicit paths.
remote-clients_1  | 
remote-clients_1  | With --update, all installed packages are updated to the latest version.
remote-clients_1  | 
remote-clients_1  | With --list, all installed and available packages are printed out.
remote-clients_1  | 
remote-clients_1  | With --licenses, show and offer the option to accept licenses for all
remote-clients_1  |      available packages that have not already been accepted.
remote-clients_1  | 
remote-clients_1  | With --version, prints the current version of sdkmanager.
remote-clients_1  | 
remote-clients_1  | Common Arguments:
remote-clients_1  |     --sdk_root=<sdkRootPath>: Use the specified SDK root instead of the SDK
remote-clients_1  |                               containing this tool
remote-clients_1  | 
remote-clients_1  |     --channel=<channelId>: Include packages in channels up to <channelId>.
remote-clients_1  |                            Common channels are:
remote-clients_1  |                            0 (Stable), 1 (Beta), 2 (Dev), and 3 (Canary).
remote-clients_1  | 
remote-clients_1  |     --include_obsolete: With --list, show obsolete packages in the
remote-clients_1  |                         package listing. With --update, update obsolete
remote-clients_1  |                         packages as well as non-obsolete.
remote-clients_1  | 
remote-clients_1  |     --no_https: Force all connections to use http rather than https.
remote-clients_1  | 
remote-clients_1  |     --proxy=<http | socks>: Connect via a proxy of the given type.
remote-clients_1  | 
remote-clients_1  |     --proxy_host=<IP or DNS address>: IP or DNS address of the proxy to use.
remote-clients_1  | 
remote-clients_1  |     --proxy_port=<port #>: Proxy port to connect to.
remote-clients_1  | 
remote-clients_1  |     --verbose: Enable verbose output.
remote-clients_1  | 
remote-clients_1  | * If the env var REPO_OS_OVERRIDE is set to "windows",
remote-clients_1  |   "macosx", or "linux", packages will be downloaded for that OS.
docker_remote-clients_1 exited with code 1

**Comment by seyrenhe** [comment]
ok, i fixed it after adding "-sdk_root=$ANDROID_SDK" on the dockerfile
