### ISSUE TITLE
execute aSPICE from another app with params

### ISSUE THREAD

**Issue by 0x501D** [iiordanov/remote-desktop-clients#288]
Hello, can I execute aSPICE from another android application with SPICE server parameters: IP, PORT, etc.

f.e.:

```
Intent sendIntent = getPackageManager().getLaunchIntentForPackage("com.iiordanov.freeaSPICE");
sendIntent.putExtra("srv_addr", "127.0.0.1");
sendIntent.putExtra("srv_port", "5555");
startActivity(sendIntent);
```

**Comment by 0x501D** [comment]
Got it, I can use url. sorry for opening this issue

**Comment by 0x501D** [comment]
```
var intent = Intent(Intent.ACTION_VIEW)
intent.setType("application/vnd.spice")
intent.setData(Uri.parse("spice://192.168.89.223:5904"))
holder.itemView.context.startActivity(intent)
```

Works fine! Thanks for this app, close this issue

**Comment by 0x501D** [comment]
Last question, can I send ssh settings via spice scheme?

**Comment by iiordanov** [comment]
Yes

This is where parameter parsing for SSH starts:

https://github.com/iiordanov/remote-desktop-clients/blob/master/bVNC/src/main/java/com/iiordanov/bVNC/ConnectionBean.java#L551

That's where the fields are defined:
https://github.com/iiordanov/remote-desktop-clients/blob/f824f89acde93f317e46c21320710fa68b8c3162/bVNC/src/main/java/com/iiordanov/bVNC/Constants.java#L60

**Comment by iiordanov** [comment]
Actually, just realized you may have been reporting a bug. If you do find that connection type is not set appropriately, please let me know and I'll reopen this bug. Please reply with a detailed description of what's wrong once you are certain, thanks!

**Comment by 0x501D** [comment]
Yes, if using ssh params, connection type is SPICE, not SPICE over ssh.

Start activity from app:

```
var intent = Intent(Intent.ACTION_VIEW)
intent.setType("application/vnd.spice")
intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
intent.setData(Uri.parse("spice://10.10.0.9:5900? 
       SshHost=10.10.0.9&SshPort=2222&SshUsername=user&SshPassword=pass"))
holder.itemView.context.startActivity(intent)
```

aSPICE using simple SPICE connection.
We can enter to aSPICE later and see requested connection:

blob:https://web.telegram.org/e540e56d-dd1c-4e05-8c3b-d504c41c4c29
blob:https://web.telegram.org/302cc495-bbdd-4b46-8e93-dc44282ca01f

**Comment by 0x501D** [comment]
Maybe we can expand scheme:

spice:// for regular SPICE proto
spice+ssh:// for SPICE over SSH

**Comment by 0x501D** [comment]
found this: public static final int SECTYPE_INTEGRATED_SSH = 24;
will try to set SecurityType to 24 and test again

**Comment by 0x501D** [comment]
Yes, when using ?SshHost=192.168.42.73&SshPort=22&SshUsername=user&SshPassword=password&SecurityType=24
connection type is set to SPICE over SSH, but aSPICE activity start failed:

```
08-02 13:27:12.778  1362  1600 I ActivityManager: Start proc 14283:com.iiordanov.freeaSPICE/u0a225 for pre-top-activity {com.iiordanov.freeaSPICE/com.iiordanov.bVNC.RemoteCanvasActivity}
08-02 13:27:12.787 14283 14283 E anov.freeaSPIC: Not starting debugger since process cannot load the jdwp agent.
08-02 13:27:12.813 14283 14283 I MultiDex: VM with version 2.1.0 has multidex support
08-02 13:27:12.813 14283 14283 I MultiDex: Installing application
08-02 13:27:12.813 14283 14283 I MultiDex: VM has multidex support, MultiDex support library is disabled.
08-02 13:27:12.813 14283 14283 I MultiDex: Installing application
08-02 13:27:12.813 14283 14283 I MultiDex: VM has multidex support, MultiDex support library is disabled.
08-02 13:27:12.813  2195  2195 D ImageWallpaper: wallpaper visibility changes to: true
08-02 13:27:12.827 14283 14283 D RemoteCanvasActivity: OnCreate called
08-02 13:27:12.829 14283 14283 W anov.freeaSPIC: Accessing hidden field Landroid/view/ViewConfiguration;->sHasPermanentMenuKey:Z (greylist-max-p, reflection, denied)
08-02 13:27:12.853  1362  8719 E WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
08-02 13:27:12.861 14283 14283 D RemoteCanvasActivity: Initializing classic connection from Intent.
08-02 13:27:12.861 14283 14283 D ConnectionBean: Creating connection from URI
08-02 13:27:12.865 14283 14283 I ConnectionBean: Parsing VNC URI.
08-02 13:27:12.867 14283 14283 D ConnectionBean: save called with database
08-02 13:27:12.876 14283 14283 D ConnectionBean: saveToSharedPreferences called
08-02 13:27:12.877 14283 14283 I ConnectionBean: URI missing VNC password.
08-02 13:27:12.877 14283 14283 D ConnectionBean: saveAndWriteRecent called
08-02 13:27:12.877 14283 14283 D ConnectionBean: saveAndWriteRecent saving
08-02 13:27:12.877 14283 14283 D ConnectionBean: saveAndWriteRecent called with database
08-02 13:27:12.879 14283 14283 D ConnectionBean: save called with database
08-02 13:27:12.889 14283 14283 D ConnectionBean: saveToSharedPreferences called
08-02 13:27:12.893 14283 14283 I RemoteCanvasActivity: Insufficent information to connect, showing connection dialog.
08-02 13:27:12.895  1362  6400 I ActivityTaskManager: START u0 {cmp=com.iiordanov.freeaSPICE/com.iiordanov.bVNC.aSPICE} from uid 10225
08-02 13:27:12.896   756   756 D android.hardware.power@1.3-service.sm6150-libperfmgr: LAUNCH: 1
08-02 13:27:12.904 14283 14283 D RemoteCanvasActivity: OnCreate complete
08-02 13:27:12.912 14283 14304 I AdrenoGLES: QUALCOMM build                   : 83a9891, Ifd6a45d56a
08-02 13:27:12.912 14283 14304 I AdrenoGLES: Build Date                       : 03/11/20
08-02 13:27:12.912 14283 14304 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.06
08-02 13:27:12.912 14283 14304 I AdrenoGLES: Local Branch                     : mybranchea639cbf-b353-f17c-80f6-1458d0b52af0
08-02 13:27:12.912 14283 14304 I AdrenoGLES: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r84-rel
08-02 13:27:12.912 14283 14304 I AdrenoGLES: Remote Branch                    : NONE
08-02 13:27:12.912 14283 14304 I AdrenoGLES: Reconstruct Branch               : NOTHING
08-02 13:27:12.912 14283 14304 I AdrenoGLES: Build Config                     : S P 8.0.12 AArch64
08-02 13:27:12.914 14283 14304 I AdrenoGLES: PFP: 0x016ee187, ME: 0x00000000
08-02 13:27:12.925   515   515 I hwservicemanager: getTransport: Cannot find entry android.hardware.graphics.mapper@3.0::IMapper/default in either framework or device manifest.
08-02 13:27:12.925 14283 14304 W Gralloc3: mapper 3.x is not supported
08-02 13:27:12.936  1362  6400 E WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
08-02 13:27:12.937  1362  1596 I ActivityTaskManager: Displayed com.iiordanov.freeaSPICE/com.iiordanov.bVNC.aSPICE: +220ms
08-02 13:27:12.964 14283 14283 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@26cc60d
08-02 13:27:12.969 14283 14283 D MainConfiguration: onCreate called
08-02 13:27:12.969 14283 14283 E MainConfiguration: Could not parse connection to edit from connID!
08-02 13:27:12.969 14283 14283 W System.err: java.lang.NumberFormatException: null
08-02 13:27:12.969 14283 14283 W System.err: 	at java.lang.Long.parseLong(Long.java:557)
08-02 13:27:12.969 14283 14283 W System.err: 	at java.lang.Long.parseLong(Long.java:636)
08-02 13:27:12.969 14283 14283 W System.err: 	at com.iiordanov.bVNC.MainConfiguration.onCreate(MainConfiguration.java:133)
08-02 13:27:12.969 14283 14283 W System.err: 	at com.iiordanov.bVNC.aSPICE.onCreate(aSPICE.java:98)
08-02 13:27:12.969 14283 14283 W System.err: 	at android.app.Activity.performCreate(Activity.java:7824)
08-02 13:27:12.969 14283 14283 W System.err: 	at android.app.Activity.performCreate(Activity.java:7813)
08-02 13:27:12.969 14283 14283 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
08-02 13:27:12.969 14283 14283 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
08-02 13:27:12.970 14283 14283 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
08-02 13:27:12.970 14283 14283 W System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
08-02 13:27:12.970 14283 14283 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-02 13:27:12.970 14283 14283 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-02 13:27:12.970 14283 14283 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
08-02 13:27:12.970 14283 14283 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-02 13:27:12.970 14283 14283 W System.err: 	at android.os.Looper.loop(Looper.java:214)
08-02 13:27:12.970 14283 14283 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
08-02 13:27:12.970 14283 14283 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-02 13:27:12.970 14283 14283 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
08-02 13:27:12.970 14283 14283 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```

**Comment by 0x501D** [comment]
I think there is a problem with ssh_password. It's not saved in aSPICE UI even if connection edited manually.
aSPICE generate prompt and ask for password anyway.

**Comment by 0x501D** [comment]
Yes, it works if we cheat aSPICE and use VncPassword instead of SshPassword.
This establish aSPICE connect activity:

?ConnectionName=Name&VncPassword=pass&SshHost=192.168.42.73&SshPort=22&SshUsername=user&SecurityType=24

We will be prompted for ssh password anyway and connection establish

**Comment by IndiaFF77** [comment]
2022/03/26 23:38:29 Android 13
Error
Copied:0 Deleted:0 Ignored:0 
Sync aborted. Wireless LAN is off.
