### ISSUE TITLE
Can not build from Scratch on MacOS

### ISSUE THREAD

**Issue by Charlesjean** [iiordanov/remote-desktop-clients#402]
Hi, I tried to build this project from scratch on MacOS, and get the following error:
Recipe 'zlib' failed at the build step 'configure'
Traceback (most recent call last):
  File "/Users/duanjinchen/10086/project/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/cerbero/build/oven.py", line 451, in _cook_recipe_step
    await ret
  File "/Users/duanjinchen/10086/project/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/cerbero/build/recipe.py", line 776, in doit
    await ret
  File "/Users/duanjinchen/10086/project/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/cerbero/build/recipe.py", line 861, in _do_step
    await run_tasks (tasks)
  File "/Users/duanjinchen/10086/project/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/cerbero/utils/__init__.py", line 669, in run_tasks
    await shutdown()
  File "/Users/duanjinchen/10086/project/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/cerbero/utils/__init__.py", line 656, in shutdown
    raise e
  File "/Users/duanjinchen/10086/project/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/cerbero/utils/__init__.py", line 663, in run_tasks
    await asyncio.gather(*tasks, return_exceptions=False)
  File "/Users/duanjinchen/10086/project/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/cerbero/build/recipe.py", line 842, in _async_run_step
    await ret
  File "/Users/duanjinchen/10086/project/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/cerbero/build/recipe.py", line 102, in async_wrapped
    await stepfunc()
  File "/Users/duanjinchen/10086/project/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/cerbero/build/build.py", line 63, in async_call
    res = await func(*args)
  File "/Users/duanjinchen/10086/project/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/cerbero/build/build.py", line 1075, in configure
    await shell.async_call(meson_cmd, self.meson_dir, logfile=self.logfile, env=self.env)
  File "/Users/duanjinchen/10086/project/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/cerbero/utils/shell.py", line 240, in async_call
    env=env)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1533, in subprocess_exec
    bufsize, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/duanjinchen/10086/project/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/build/build-tools/bin/meson': '/Users/duanjinchen/10086/project/remote-desktop-clients/remoteClientLib/jni/libs/cerbero/build/build-tools/bin/meson'
Select an action to proceed:

It seems cerbero failed to build these libraries. Did you test the build script on MacOS? Really need help to solve this, thank you.

**Comment by iiordanov** [comment]
This is not supported. Please use the provided Docker build method

I-b From Scratch with Docker

by first installing Docker on your Mac.
